feat(effects): make resubscription handler overridable (#2295)
Closes #2294

BREAKING CHANGE:

`resubscribeOnError` renamed to `useEffectsErrorHandler` in `createEffect` metadata

BEFORE:

```ts
  class MyEffects {
    effect$ = createEffect(() => stream$, {
      resubscribeOnError: true, // default
    });
  }
```

AFTER:

```ts
  class MyEffects {
    effect$ = createEffect(() => stream$, {
      useEffectsErrorHandler: true, // default
    });
  }
```